--CLIENTS
INSERT INTO ALT_CLIENT VALUES(1, 'CRISTIAN', 'NARANJO');
INSERT INTO ALT_CLIENT VALUES(2, 'EMILIO', 'BARRIONUEVO');
INSERT INTO ALT_CLIENT VALUES(3, 'EMILIO', 'GAVILANEZ');

--ITEMS
INSERT INTO ALT_ITEM VALUES('PER_ART01', 'Articulo 1', 12.25);
INSERT INTO ALT_ITEM VALUES('PER_ART02', 'Articulo 2', 10);
INSERT INTO ALT_ITEM VALUES('PER_ART03', 'Articulo 3', 125);

--ORDER
INSERT INTO ALT_ORDER VALUES(1, 1, CURRENT_TIMESTAMP());
INSERT INTO ALT_ORDER VALUES(2, 1, CURRENT_TIMESTAMP());

--ORDER_ITEM
INSERT INTO ALT_ORDER_ITEM VALUES(1, 1, 'PER_ART01', 2, 12.25);
INSERT INTO ALT_ORDER_ITEM VALUES(2, 1, 'PER_ART02', 3, 10);
INSERT INTO ALT_ORDER_ITEM VALUES(1, 2, 'PER_ART01', 2, 12.25);
INSERT INTO ALT_ORDER_ITEM VALUES(2, 2, 'PER_ART02', 3, 10);
INSERT INTO ALT_ORDER_ITEM VALUES(3, 2, 'PER_ART03', 3, 120);
