--TABLES
CREATE TABLE ALT_CLIENT(
ID_CLIENT INT NOT NULL,
FIRST_NAME VARCHAR(60) NOT NULL,
LAST_NAME VARCHAR(60) NOT NULL,
CONSTRAINT PK_CLIENT PRIMARY KEY (ID_CLIENT)
);

CREATE TABLE ALT_ORDER (
ID_ORDER INT NOT NULL,
ID_CLIENT INT NOT NULL,
ORDER_DATE DATE NOT NULL,
CONSTRAINT FK_ORDER PRIMARY KEY (ID_ORDER),
CONSTRAINT FK_CLIENT_ORDER FOREIGN KEY (ID_CLIENT)  REFERENCES ALT_CLIENT(ID_CLIENT));

CREATE TABLE ALT_ITEM (
ID_ITEM VARCHAR(10) NOT NULL,
NAME VARCHAR(50) NOT NULL,
UNIT_PRICE DECIMAL(5,2),
CONSTRAINT PK_ITEM PRIMARY KEY (ID_ITEM));

CREATE TABLE ALT_ORDER_ITEM (
ID_ORDER_ITEM INT NOT NULL,
ID_ORDER INT NOT NULL,
ID_ITEM VARCHAR(10) NOT NULL,
QUANTITY INT,
PRICE DECIMAL(5,2),
CONSTRAINT PK_ORDER_ITEM PRIMARY KEY (ID_ORDER_ITEM, ID_ORDER),
CONSTRAINT FK_ORDER_ITEM FOREIGN KEY (ID_ORDER)  REFERENCES ALT_ORDER(ID_ORDER),
CONSTRAINT FK_ITEM_ORDER FOREIGN KEY (ID_ITEM)  REFERENCES ALT_ITEM(ID_ITEM));

--SEQUENCES
CREATE SEQUENCE IF NOT EXISTS ALT_SEQ_CLIENT START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS ALT_SEQ_ORDER START WITH 1
INCREMENT BY 1;